SCREEN_WIDTH = 288
SCREEN_HEIGHT = 512
FPS = 75

GRAVITY = 0.35

FLAP_KEY = 'K_SPACE'
CLOSE_KEY = 'K_r'
BIRD_FLAP_RADIUS = 5
BIRD_ANIMATION_SPEED = 12
BIRD_APPEARING_SPEED = 2.5
BIRD_Y_POSITION = SCREEN_WIDTH / 5.76